### ISSUE TITLE
Adding LinearRegression component

### ISSUE THREAD

**Issue by scroobiustrip** [tingiskhan/numpyro-sts#5]
Hey, thank you for adding this great library - this is less of an issue and more of a feature request - but would it possible to add a `LinearRegression` component to the package as well?

Feel as though, then it would be on par with the [sts-jax](https://github.com/probml/sts-jax) library, but would be in my preferred PPL of choice (numpyro!) 😅.

Or can it be as simple as adding `X @ betas` to your model?

In any case, many thanks!

**Comment by scroobiustrip** [comment]
Ah awesome, okay in which case I shall proceed with that for now! 😄 

But yeah, if you ever do decide to add it as an additional component I'd obviously be very grateful - but this should be more than enough for now, massive thanks!

**Comment by tingiskhan** [comment]
Sounds great! No problem, thank you for using the library!
